name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./user-management/pom.xml
          mvn clean package -f ./driver-management/pom.xml
          mvn clean package -f ./vehicle-management/pom.xml

      - name: Docker Build and push for UserManagement
        uses: docker/build-push-action@v4
        with:
          context: ./user-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user-management:latest
            ghcr.io/${{ github.repository }}/user-management:${{ github.ref_name }}
            
      - name: Docker Build and push for DriverManagement
        uses: docker/build-push-action@v4
        with:
          context: ./driver-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/driver-management:latest
            ghcr.io/${{ github.repository }}/driver-management:${{ github.ref_name }}
            
      - name: Docker Build and push for VehicleManagement
        uses: docker/build-push-action@v4
        with:
          context: ./vehicle-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/vehicle-management:latest
            ghcr.io/${{ github.repository }}/vehicle-management:${{ github.ref_name }}
            
