server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: user-management
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, 
        - id: driver-management
          uri: http://localhost:8083
          predicates:
            - Path=/drivers/**, 
        - id: vehicle-management
          uri: http://localhost:8084
          predicates:
            - Path=/vehicles/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: http://userManagement:8080
          predicates:
            - Path=/users/**, 
        - id: driver-management
          uri: http://driverManagement:8080
          predicates:
            - Path=/drivers/**, 
        - id: vehicle-management
          uri: http://vehicleManagement:8080
          predicates:
            - Path=/vehicles/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
