---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  labels:
    app: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: username/user-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-management
  labels:
    app: driver-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-management
  template:
    metadata:
      labels:
        app: driver-management
    spec:
      containers:
        - name: driver-management
          image: username/driver-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-management
  labels:
    app: vehicle-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-management
  template:
    metadata:
      labels:
        app: vehicle-management
    spec:
      containers:
        - name: vehicle-management
          image: username/vehicle-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: user-management
  labels:
    app: user-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-management


---


apiVersion: v1
kind: Service
metadata:
  name: driver-management
  labels:
    app: driver-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: driver-management


---


apiVersion: v1
kind: Service
metadata:
  name: vehicle-management
  labels:
    app: vehicle-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: vehicle-management

